### ISSUE TITLE
cannot load system

### ISSUE THREAD

**Issue by boostbob** [roja/system#4]
```
#gem list | grep system                                                                      
system (0.1.3)
```

irb, require error:

```
2.0.0-p195 :001 > require 'system'
LoadError: cannot load such file -- version
    from /Users/bob/.rvm/gems/ruby-2.0.0-p195@rails-4.0.0/gems/system-0.1.3/lib/system.rb:5:in `require'
    from /Users/bob/.rvm/gems/ruby-2.0.0-p195@rails-4.0.0/gems/system-0.1.3/lib/system.rb:5:in `<top (required)>'
    from /Users/bob/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
    from /Users/bob/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in require'
    from /Users/bob/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
    from (irb):1
    from /Users/bob/.rvm/rubies/ruby-2.0.0-p195/bin/irb:16:in `<main>'
```

**Comment by RyanScottLewis** [comment]
Looks like the `version` gem isn't properly setup as a dependency in the gemspec.

To get past it for now, you can `gem install version` or add `gem 'version', '~> 1.0.0`` to your Gemfile

**Comment by boostbob** [comment]
okay, thanks.
